"""Third commit, adding created at

Revision ID: 6b3b8bf8b25a
Revises: 66f4925f1787
Create Date: 2025-01-24 14:43:25.421522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3b8bf8b25a'
down_revision: Union[str, None] = '66f4925f1787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_session', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('user_session', 'created_at')
    # ### end Alembic commands ###
